CREATE TABLE `player` (
  `PLAYER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `CRICKET_TEAM` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`PLAYER_ID`) USING BTREE
);
 
CREATE TABLE `cricket_match` (
  `MATCH_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `SERIES_NAME` VARCHAR(20) NOT NULL,
  `LOCATION` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`MATCH_ID`) USING BTREE
);

CREATE TABLE  `player_match` (
  `PLAYER_ID` INT(10) UNSIGNED NOT NULL,
  `MATCH_ID` INT(10) UNSIGNED NOT NULL,
  `SCORE` INT(4) NOT NULL,
  PRIMARY KEY (`PLAYER_ID`,`MATCH_ID`),
  CONSTRAINT `FK_PLAYER_ID` FOREIGN KEY (`PLAYER_ID`) 
             REFERENCES `player` (`PLAYER_ID`),
  CONSTRAINT `FK_MATCH_ID` FOREIGN KEY (`MATCH_ID`) 
             REFERENCES `cricket_match` (`MATCH_ID`)
);